[package]
name = "rust-system-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
iced = { version = "0.10", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }

